# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x-3dhwlZ3C9pqW3dV7gumNnywSUZxkcc
"""

import json
import time
import numpy as np
import pandas as pd


def simulate_driver_facial_cues(total_frames=300, seed=42):
  """Generates realistic Mouth Aspect Ratio (MAR) sequence simulating a driver.

  Includes baseline talking/resting, transient speech spikes, and extended
  yawns.
  """
  np.random.seed(seed)

  # Baseline normal speaking/resting MAR (~0.15 - 0.25)
  mar_series = np.random.normal(loc=0.20, scale=0.04, size=total_frames)
  gt_series = np.zeros(total_frames, dtype=int)

  # Yawn Event 1: Frames 50 to 90 (40 frames = ~1.33 seconds at 30 FPS)
  mar_series[50:90] += np.random.normal(loc=0.50, scale=0.05, size=40)
  gt_series[50:90] = 1

  # Speech Noise Spike (Talking): Frames 130 to 135 (5 frames = short speech artifact)
  mar_series[130:135] += np.random.normal(loc=0.38, scale=0.04, size=5)

  # Yawn Event 2: Frames 180 to 230 (50 frames = ~1.66 seconds at 30 FPS)
  mar_series[180:230] += np.random.normal(loc=0.55, scale=0.05, size=50)
  gt_series[180:230] = 1

  # Clip MAR values to valid physical limits [0.10, 0.95]
  mar_series = np.clip(mar_series, 0.10, 0.95)
  return mar_series, gt_series


def evaluate_yawn_detector(
    mar_series, gt_series, mar_threshold=0.50, persistence_frames=10
):
  """Evaluates frame-level yawn cues using MAR thresholding and temporal persistence.

  Calculates Precision, Recall, F1-Score, FP/FN counts, and frame latency.
  """
  preds = np.zeros(len(mar_series), dtype=int)
  consecutive_high = 0
  start_time = time.time()

  for i, val in enumerate(mar_series):
    if val >= mar_threshold:
      consecutive_high += 1
    else:
      consecutive_high = 0

    if consecutive_high >= persistence_frames:
      preds[i] = 1

  latency_ms = ((time.time() - start_time) / len(mar_series)) * 1000.0

  tp = int(np.sum((preds == 1) & (gt_series == 1)))
  fp = int(np.sum((preds == 1) & (gt_series == 0)))
  tn = int(np.sum((preds == 0) & (gt_series == 0)))
  fn = int(np.sum((preds == 0) & (gt_series == 1)))

  precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
  recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
  f1 = (
      2 * precision * recall / (precision + recall)
      if (precision + recall) > 0
      else 0.0
  )

  return {
      "Config": f"MAR>={mar_threshold}, Win={persistence_frames}f",
      "MAR_Thresh": mar_threshold,
      "Persistence_Frames": persistence_frames,
      "Precision": round(precision, 3),
      "Recall": round(recall, 3),
      "F1_Score": round(f1, 3),
      "FP_Frames": fp,
      "FN_Frames": fn,
      "Latency_ms": round(latency_ms, 4),
  }


if __name__ == "__main__":
  print("=========================================================")
  print(" SG-3 YAWN & FACIAL-CUE ANALYSIS EXPERIMENT (WEEK 5)")
  print(" Stream B: Driver Drowsiness Monitoring System")
  print("=========================================================\n")

  mar_series, gt_series = simulate_driver_facial_cues()

  configurations = [
      {"mar_thresh": 0.40, "persistence": 1},  # Config 1: High sensitivity
      {"mar_thresh": 0.50, "persistence": 1},  # Config 2: Baseline frame-level
      {
          "mar_thresh": 0.50,
          "persistence": 10,
      },  # Config 3: Geometric + 10-frame window (~0.33s)
      {
          "mar_thresh": 0.60,
          "persistence": 15,
      },  # Config 4: High threshold + 15-frame window (~0.5s)
  ]

  results = [
      evaluate_yawn_detector(
          mar_series, gt_series, c["mar_thresh"], c["persistence"]
      )
      for c in configurations
  ]

  df = pd.DataFrame(results)
  print("--- WEEK 5 EXPERIMENTAL RESULTS TABLE ---")
  print(df.to_string(index=False))
  print("\n---------------------------------------------------------")

  # Export V1 Interface Sample Output
  sample_v1_output = {
      "frame_id": 205,
      "mouth_aspect_ratio": 0.68,
      "mar_threshold": 0.50,
      "yawn_cue_detected": True,
      "consecutive_yawn_frames": 25,
      "confidence": 0.92,
      "processing_time_ms": 0.12,
  }

  with open("sg3_v1_output_sample.json", "w") as f:
    json.dump(sample_v1_output, f, indent=4)

  print(
      "[SUCCESS] Verified V1 output schema written to"
      " 'sg3_v1_output_sample.json'"
  )